import { ExchangeConfig } from '../types';

export const EXCHANGE_CONFIGS: Record<string, ExchangeConfig> = {
  binance: {
    id: 'binance',
    name: 'binance',
    displayName: 'Binance',
    logo: '🟡',
    description: 'Maior exchange global com melhor liquidez',
    website: 'https://www.binance.com',
    supported_regions: ['Global', 'Brasil'],
    features: ['Spot Trading', 'Futures', 'Staking'],
  },
  okex: {
    id: 'okex',
    name: 'okex',
    displayName: 'OKEx',
    logo: '⚪',
    description: 'Exchange líder com alto volume e derivativos',
    website: 'https://www.okx.com',
    supported_regions: ['Global', 'Brasil'],
    features: ['Spot Trading', 'Futures', 'Perpetual', 'Staking'],
  },
  bitso: {
    id: 'bitso',
    name: 'bitso',
    displayName: 'Bitso',
    logo: '🔵',
    description: 'Exchange latino-americana com foco em pagamentos',
    website: 'https://bitso.com',
    supported_regions: ['Latinoamérica', 'Brasil'],
    features: ['Spot Trading', 'Conversão'],
  },
  toro: {
    id: 'toro',
    name: 'toro',
    displayName: 'Toro',
    logo: '🟢',
    description: 'Plataforma brasileira com múltiplos ativos',
    website: 'https://www.toro.com',
    supported_regions: ['Brasil'],
    features: ['Spot Trading', 'Copytrading'],
  },
  gateio: {
    id: 'gateio',
    name: 'gateio',
    displayName: 'Gate.io',
    logo: '🟦',
    description: 'Exchange descentralizada com altcoins diversos',
    website: 'https://www.gate.io',
    supported_regions: ['Global', 'Brasil'],
    features: ['Spot Trading', 'Futures', 'Lending'],
  },
  bybit: {
    id: 'bybit',
    name: 'bybit',
    displayName: 'Bybit',
    logo: '🟨',
    description: 'Exchange especializada em derivativos e futures',
    website: 'https://www.bybit.com',
    supported_regions: ['Global', 'Brasil'],
    features: ['Futures', 'Spot Trading', 'Perpetual'],
  },
  mexc: {
    id: 'mexc',
    name: 'mexc',
    displayName: 'MEXC',
    logo: '🔶',
    description: 'Exchange com foco em novos projetos e altcoins',
    website: 'https://www.mexc.com',
    supported_regions: ['Global', 'Brasil'],
    features: ['Spot Trading', 'Futures', 'Launchpad'],
  },
};

export const EXCHANGE_LIST = Object.values(EXCHANGE_CONFIGS);
